# OpenAI API
[api]
api_key = ""
engine = "text-davinci-003"
prompt_intro = """Generate a short summary that describes the capabilities of the GitHub project {}."""
prompt_slogan = """Generate a slogan for the GitHub project {}."""
temperature = 0.5
max_tokens = 100
top_p = 1.0
frequency_penalty = 0.0
presence_penalty = 0.0

# GitHub Repository
[github]
url = "https://github.com/eli64s/readme-ai" #"https://github.com/nofoobar/JobBoard-Fastapi"
owner = ""
repo_name = ""

# Paths
[paths]
file_extensions = "file_extensions.toml"
file_names = "file_names.toml"
setup_guide = "setup_guide.toml"
badges = "conf/badges.json"
docs = "docs/raw_data.csv"
md = "docs/README.md"

# Markdown template
[md]
head = """\n<div align="center">
<h1 align="center">
<img src="https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/ec559a9f6bfd399b82bb44393651661b08aaf7ba/icons/folder-markdown-open.svg" width="100" />
<br>
{}
</h1>
<h3 align="center">📍 {}</h3>
<h3 align="center">🚀 Developed with the software and tools below.</h3>
<p align="center">
\n{}
</p>
\n</div>
\n---
"""

toc = """
## 📚 Table of Contents
- [📚 Table of Contents](#-table-of-contents)
- [📍Overview](#-introdcution)
- [🔮 Features](#-features)
- [⚙️ Project Structure](#project-structure)
- [🧩 Modules](#modules)
- [🏎💨 Getting Started](#-getting-started)
- [🗺 Roadmap](#-roadmap)
- [🤝 Contributing](#-contributing)
- [🪪 License](#-license)
- [📫 Contact](#-contact)
- [🙏 Acknowledgments](#-acknowledgments)
\n---
"""

intro = """
\n## 📍Overview
\n{}
\n## 🔮 Feautres
\n> `[📌  INSERT-PROJECT-FEATURES]`
\n---
"""

modules = """
\n---
\n<img src="https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/ec559a9f6bfd399b82bb44393651661b08aaf7ba/icons/folder-src-open.svg" width="80" />
\n## 💻 Modules
"""
dropdown = """<details closed><summary>{}</summary>\n\n{}\n\n</details>\n"""

tree = """
\n<img src="https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/ec559a9f6bfd399b82bb44393651661b08aaf7ba/icons/folder-github-open.svg" width="80" />
\n## ⚙️ Project Structure\n
"""

setup = """<hr />
\n## 🚀 Getting Started
\n### ✅ Prerequisites
\nBefore you begin, ensure that you have the following prerequisites installed:
> `[📌  INSERT-PROJECT-PREREQUISITES]`
\n### 💻 Installation
\n1. Clone the {} repository:
```sh\ngit clone {}\n```
\n2. Change to the project directory:
```sh\ncd {}\n```
\n3. Install the dependencies:
```sh\n{}\n```
\n### 🤖 Using {}
\n```sh\n{}\n```
\n### 🧪 Running Tests
```sh\n#run tests\n```
\n<hr />
"""

close = """
\n## 🛠 Future Development
- [X] [📌  COMPLETED-TASK]
- [ ] [📌  INSERT-TASK]
- [ ] [📌  INSERT-TASK]

\n---

## 🤝 Contributing
Contributions are always welcome! Please follow these steps:
1. Fork the project repository. This creates a copy of the project on your account that you can modify without affecting the original project.
2. Clone the forked repository to your local machine using a Git client like Git or GitHub Desktop.
3. Create a new branch with a descriptive name (e.g., `new-feature-branch` or `bugfix-issue-123`).
```sh
git checkout -b new-feature-branch
```
4. Make changes to the project's codebase.
5. Commit your changes to your local branch with a clear commit message that explains the changes you've made.
```sh
git commit -m 'Implemented new feature.'
```
6. Push your changes to your forked repository on GitHub using the following command
```sh
git push origin new-feature-branch
```
7. Create a pull request to the original repository.
Open a new pull request to the original project repository. In the pull request, describe the changes you've made and why they're necessary. 
The project maintainers will review your changes and provide feedback or merge them into the main branch.
\n---

## 🪪 License

This project is licensed under the `[📌  INSERT-LICENSE-TYPE]` License. See the [LICENSE](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) file for additional info.
\n---

## 🙏 Acknowledgments

[📌  INSERT-DESCRIPTION]

\n---\n
"""